// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfniAaKe5rtbThcmarmrnRi-mNATzKIM',
    appId: '1:944409081770:web:1dc35138cb46b997d35dd3',
    messagingSenderId: '944409081770',
    projectId: 'the-inventory-app1',
    authDomain: 'the-inventory-app1.firebaseapp.com',
    storageBucket: 'the-inventory-app1.firebasestorage.app',
    measurementId: 'G-SVMY1XT9X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBLo9NKTLEeermFo9OWvXzfxqtAHu9eo',
    appId: '1:944409081770:android:a5a7215c089533c4d35dd3',
    messagingSenderId: '944409081770',
    projectId: 'the-inventory-app1',
    storageBucket: 'the-inventory-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_CNVAljEoWU1NCdg6fUD6nZfEiEOBkD0',
    appId: '1:944409081770:ios:f8d89c8823dbc20fd35dd3',
    messagingSenderId: '944409081770',
    projectId: 'the-inventory-app1',
    storageBucket: 'the-inventory-app1.firebasestorage.app',
    iosBundleId: 'com.example.theInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPfniAaKe5rtbThcmarmrnRi-mNATzKIM',
    appId: '1:944409081770:web:230913e80daf4884d35dd3',
    messagingSenderId: '944409081770',
    projectId: 'the-inventory-app1',
    authDomain: 'the-inventory-app1.firebaseapp.com',
    storageBucket: 'the-inventory-app1.firebasestorage.app',
    measurementId: 'G-T00TKRHEVH',
  );
}
